### PR TITLE
Support for nowait queries

### PR DESCRIPTION
**Pull request by schellj**
Support for nowait queries, i.e., immediately return an error when attempting to select a locked record instead of waiting for the lock to be released.

Note that the first two commits are while-you're-at-it fixes.

## Related PRs
gudtech/gt-core#213
gudtech/gt-processor#101

### CODE REVIEW

**Comment by schellj** [comment]
Note that I replaced the warning in favor of an error for unsupported db version in the `nowait`.  That method fundamentally does not perform the spirit `nowait` if the db version isn't supported, so I think an error is more appropriate (not to mention more visible).

**Comment by ropsmarv** [comment]
Regarding the first two commits:

I wondered for a bit about why we needed to invoke `_log` _in addition to_ `_error`, since `_error` actually invokes `_log`.  But then I realized that the messages sent to the two different functions had different content.

All these underscore functions like `_log`, `_error`, and such are confusing because they violate the convention that prepending an underscore implies "private".

From what I can tell, it's not `_error` itself which assumes hashref, but `_session`.  From spelunking DBR::Common, it looks to me like the design intent is to have implementing classes override `_session`. (This really ought to be documented in DBR::Common, if true.) So rather than use `$self->[f_query]->_error` as a workaround, perhaps `sub _session { shift->[f_query]->_session }` could solve the problem for all of ResultSet rather than just this one location.

**Comment by ropsmarv** [comment]
Regarding the primary commit:

Since it is public, the `nowait` method should be documented as such.

It would be helpful if the `OptimizerHints` and `MaxExecutionTime` packages were documented (both the packages themselves, and the individual methods/subs).  If a package is not yet intended to have a public interface, documenting via line comments rather than POD would work.

It looks like OptimizerHints only get applied to SELECT queries, but from the name it seems like
they could also be applied to INSERT and such.

Regarding the testing commit:

Optionally, consider using `local` to limit the scope of a monkeypatched method in order to inoculate against later test code which may misbehave if the maintainer does not realize that behavior has been hacked.

...

No blocking concerns.  Nice work!

**Review by ropsmarv — APPROVED** [review]

**Comment by schellj** [comment]
@ropsmarv Good points, which I have pushed updates for.

**Pull request merged**
